language: java
jdk:
   - openjdk8

branches:
  only:
    - master

chche:
  directories:
    - $HOME/.m2
before_deploy:
  - zip -r flatform42-api-service *
  - mkdir -p deploy
  - mv flatform42-api-service.zip deploy/flatform42-api-service.zip
  
notifications:
  email:
    recipients:
      - mydream11123@naver.com
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: flatform42-api-deploy # 6-3-3에서 생성한 S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
    on:
      repo: potato-CYH/Hakerton_42Flatform_API_Server #Github 주소
      branch: master
  
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: flatform42-api-deploy # S3 버킷
    key: flatform42-api-service.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip
    application: flatform42-api-service # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: flatform42-api-service-group # 웹_ 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      repo: jojoldu/springboot-webservice
      branch: master
